(* DO NOT EDIT THIS FILE *)
let e:exn = Game.Illegal
let check_init_state : Yojson.Basic.json -> Game.state = Game.init_state
let check_max_score : Game.state -> int = Game.max_score
let check_score : Game.state -> int = Game.score
let check_turns : Game.state -> int = Game.turns
let check_current_room_id : Game.state -> string = Game.current_room_id
let check_inv : Game.state -> string list = Game.inv
let check_visited : Game.state -> string list = Game.visited
let check_locations : Game.state -> (string*string) list = Game.locations
let check_do' : string -> Game.state -> Game.state = Game.do'
